# Generated by Django 3.0.2 on 2020-02-04 09:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NivelDet',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nivel_tec', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='P_detal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='P_opci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='unidad2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_unidad', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='sop_notif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Solo letras para el nombre por favor.', regex='^[a-zA-ZñÑ]+$')])),
                ('num_pc', models.IntegerField()),
                ('problemaAd', models.CharField(max_length=500)),
                ('estado_sop', models.IntegerField(null=True)),
                ('cod_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to=settings.AUTH_USER_MODEL)),
                ('descrip1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soporte.P_detal')),
                ('tipo_sop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soporte.P_opci')),
                ('usu_tec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tecnico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='p_detal',
            name='p_opci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soporte.P_opci'),
        ),
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombre', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Solo letras para el nombre por favor.', regex='^[a-zA-ZñáéíóúäëïöüÑ\\s]+$')])),
                ('apellido', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Solo letras para el apellido por favor.', regex='^[a-zA-ZñáéíóúäëïöüÑ\\s]+$')])),
                ('cedula', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000000, message='cedula no valida.'), django.core.validators.MaxValueValidator(35000000, message='cedula no valida.')])),
                ('email', models.EmailField(max_length=254, null=True)),
                ('fedicion', models.DateTimeField(blank=True, null=True)),
                ('cod_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soporte.unidad2')),
            ],
        ),
    ]
