# Generated by Django 3.0.2 on 2020-02-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveldet',
            name='nivel_coord_area',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='niveldet',
            name='nivel_sec',
            field=models.BooleanField(default=False),
        ),
    ]
