# Generated by Django 3.0.2 on 2020-02-06 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0003_auto_20200204_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigos',
            name='cod_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soporte.unidad2'),
        ),
        migrations.AddField(
            model_name='codigos',
            name='sub_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soporte.sub_area'),
        ),
        migrations.AddField(
            model_name='datos',
            name='codigoRe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soporte.Codigos'),
        ),
    ]
