# Generated by Django 2.2.2 on 2019-11-12 20:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('soporte', '0003_datosprev'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombre', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Solo letras para el nombre por favor.', regex='^[a-zA-ZñÑ]+$')])),
                ('apellido', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Solo letras para el nombre por favor.', regex='^[a-zA-ZñÑ]+$')])),
                ('manzana', models.IntegerField()),
                ('cedula', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('fedicion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DatosPrev',
        ),
    ]
