# Generated by Django 2.2.2 on 2019-11-12 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0004_auto_20191112_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos',
            name='manzana',
        ),
    ]
