# Generated by Django 3.0.2 on 2020-02-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0004_auto_20200206_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelesNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_nivel', models.CharField(max_length=200)),
            ],
        ),
    ]
