# Generated by Django 2.2.2 on 2019-11-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0005_remove_datos_manzana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
