# Generated by Django 3.0.2 on 2020-02-13 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0005_nivelesnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='codigos',
            name='nivel_num',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='soporte.NivelesNum'),
        ),
    ]
