# Generated by Django 2.2.2 on 2019-11-25 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soporte', '0007_auto_20191124_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='sop_notif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_usu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to=settings.AUTH_USER_MODEL)),
                ('descrip1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soporte.P_detal')),
                ('tipo_sop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soporte.P_opci')),
                ('usu_tec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tecnico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
