# Generated by Django 3.0.2 on 2020-02-14 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0007_auto_20200213_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigos',
            name='sub_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soporte.P_opci'),
        ),
        migrations.AlterField(
            model_name='datos',
            name='sub_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soporte.P_opci'),
        ),
    ]
