# Generated by Django 2.2.2 on 2019-11-27 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0008_sop_notif'),
    ]

    operations = [
        migrations.AddField(
            model_name='sop_notif',
            name='nombre',
            field=models.CharField(default='pepe', max_length=200, validators=[django.core.validators.RegexValidator(message='Solo letras para el nombre por favor.', regex='^[a-zA-ZñÑ]+$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sop_notif',
            name='num_pc',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
