# Generated by Django 3.0.2 on 2020-02-14 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0008_auto_20200214_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigos',
            name='nivel_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soporte.NivelesNum', unique=True),
        ),
    ]
