# Generated by Django 2.2.2 on 2019-11-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0009_auto_20191127_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='sop_notif',
            name='problemaAd',
            field=models.CharField(default='hola', max_length=500),
            preserve_default=False,
        ),
    ]
