# Generated by Django 2.2.2 on 2019-11-27 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0010_sop_notif_problemaad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sop_notif',
            name='descrip1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soporte.P_detal'),
        ),
    ]
