# Generated by Django 2.2.2 on 2019-11-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0011_auto_20191127_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='cod_area',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='datos',
            name='cod_nivel',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sop_notif',
            name='estado_sop',
            field=models.IntegerField(null=True),
        ),
    ]
