# Generated by Django 3.0.1 on 2019-12-22 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0012_auto_20191127_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='apellido',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Solo letras para el apellido por favor.', regex='^[a-zA-ZñÑ\\s]+$')]),
        ),
    ]
