# Generated by Django 3.0.2 on 2020-02-18 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0012_auto_20200218_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='nivel_usua',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='soporte.NivelesNum'),
        ),
    ]
