# Generated by Django 3.0.1 on 2019-12-22 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0013_auto_20191222_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='nombre',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Solo letras para el nombre por favor.', regex='^[a-zA-ZñÑ\\s]+$')]),
        ),
    ]
