# Generated by Django 3.0.2 on 2020-01-25 23:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0014_auto_20191222_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='cedula',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(100, message='cedula no valida.'), django.core.validators.MaxValueValidator(105)]),
        ),
    ]
