# Generated by Django 3.0.2 on 2020-01-25 23:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0015_auto_20200125_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='cedula',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(100, message='cedula no valida.'), django.core.validators.MaxValueValidator(105, message='cedula no valida.')]),
        ),
    ]
