# Generated by Django 3.0.2 on 2020-04-04 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0016_auto_20200305_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='report_usu_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soporte.unidad2')),
            ],
        ),
    ]
