# Generated by Django 3.0.2 on 2020-01-25 23:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0016_auto_20200125_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='cedula',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1000000, message='cedula no valida.'), django.core.validators.MaxValueValidator(35000000, message='cedula no valida.')]),
        ),
    ]
