# Generated by Django 3.0.2 on 2020-01-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0017_auto_20200125_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='unidad2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_unidad', models.CharField(max_length=500)),
            ],
        ),
    ]
