# Generated by Django 3.0.2 on 2020-04-04 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soporte', '0017_report_usu_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_usu_area',
            name='id',
        ),
        migrations.AddField(
            model_name='report_usu_area',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
