# Generated by Django 3.0.2 on 2020-01-26 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0018_unidad2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='unidad2',
        ),
    ]
