# Generated by Django 3.0.2 on 2020-04-04 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0019_auto_20200403_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_usu_area',
            name='nivel_usua',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soporte.NivelesNum'),
        ),
        migrations.AlterField(
            model_name='report_usu_area',
            name='cod_area',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='soporte.unidad2'),
        ),
    ]
