# Generated by Django 3.0.2 on 2020-04-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0020_auto_20200404_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='bienes_gob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
