# Generated by Django 3.0.2 on 2020-01-26 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0021_auto_20200126_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='cod_area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='soporte.unidad2'),
            preserve_default=False,
        ),
    ]
