# Generated by Django 3.0.2 on 2020-04-09 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0021_bienes_gob'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bienes_gob',
            new_name='bienes_gob_categoria',
        ),
    ]
