# Generated by Django 3.0.2 on 2020-04-09 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0022_auto_20200409_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='bie_gob_bienes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_e', models.IntegerField(unique=True)),
                ('cantidad', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('idunidad', models.IntegerField()),
                ('idcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soporte.bienes_gob_categoria')),
            ],
        ),
    ]
