# Generated by Django 3.0.2 on 2020-04-09 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0023_bie_gob_bienes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bie_gob_bienes',
            name='idunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soporte.unidad2'),
        ),
    ]
