# Generated by Django 3.0.2 on 2020-04-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0024_auto_20200409_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bie_gob_bienes',
            name='codigo_e',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
