# Generated by Django 3.0.2 on 2020-04-10 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0025_auto_20200409_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sop_notif',
            name='tipo_sop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soporte.P_opci'),
        ),
    ]
