# Generated by Django 3.0.2 on 2020-04-10 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0027_estado_soporte_notif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sop_notif',
            name='estado_sop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soporte.estado_soporte_notif'),
        ),
    ]
