# Generated by Django 3.0.2 on 2020-04-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0029_auto_20200410_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='sop_notif',
            name='fecha_pub',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
