# Generated by Django 3.0.2 on 2020-04-10 17:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0030_sop_notif_fecha_pub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sop_notif',
            name='fecha_pub',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 10, 17, 14, 24, 182544, tzinfo=utc)),
        ),
    ]
