# Generated by Django 3.0.2 on 2020-04-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0031_auto_20200410_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sop_notif',
            name='fecha_pub',
            field=models.DateTimeField(blank=True),
        ),
    ]
