# Generated by Django 3.0.2 on 2020-04-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0033_auto_20200410_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sop_notif',
            name='num_pc',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
