# Generated by Django 3.0.2 on 2020-04-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0035_auto_20200410_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='sop_notif',
            name='categoria_e',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
