# Generated by Django 3.0.2 on 2020-04-11 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0037_sop_notif_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sop_notif_mes',
            name='estado_sop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soporte.estado_soporte_notif'),
        ),
        migrations.AddField(
            model_name='sop_notif_mes',
            name='tipo_sop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soporte.P_opci'),
        ),
    ]
