# Generated by Django 3.0.2 on 2020-04-11 03:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0039_auto_20200410_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='sop_notif_mes',
            name='fecha_pub',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 11, 3, 25, 11, 839194, tzinfo=utc)),
        ),
    ]
