# Generated by Django 3.0.2 on 2020-04-11 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0042_auto_20200410_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sop_notif_mes',
            old_name='cod_usu',
            new_name='usu_tec',
        ),
    ]
