# Generated by Django 3.0.2 on 2020-04-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0043_auto_20200411_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sop_notif',
            name='nombre_e',
            field=models.CharField(blank=True, max_length=190, null=True),
        ),
        migrations.AlterField(
            model_name='sop_notif_mes',
            name='mensaje',
            field=models.CharField(max_length=500),
        ),
    ]
