# Generated by Django 3.0.5 on 2020-06-13 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soporte', '0044_auto_20200412_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='asistencias_p',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_a', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='asistencia_personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_emple', models.DateTimeField()),
                ('n_asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soporte.asistencias_p')),
                ('n_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
