# Generated by Django 3.0.5 on 2020-06-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0045_asistencia_personal_asistencias_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia_personal',
            name='inasistente',
            field=models.BooleanField(default=False),
        ),
    ]
