# Generated by Django 3.0.5 on 2020-06-15 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0046_asistencia_personal_inasistente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia_personal',
            old_name='inasistente',
            new_name='asistente',
        ),
    ]
