# Generated by Django 3.0.5 on 2020-06-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0047_auto_20200615_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia_personal',
            name='a_emple',
            field=models.DateTimeField(null=True),
        ),
    ]
