# Generated by Django 3.0.5 on 2020-06-21 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soporte', '0048_auto_20200618_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='reset_contra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recuperada', models.BooleanField(default=False)),
                ('fecha_soli', models.DateTimeField()),
                ('usuario_x', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
