# Generated by Django 3.0.5 on 2020-06-24 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soporte', '0051_auto_20200622_0435'),
    ]

    operations = [
        migrations.CreateModel(
            name='permisos_emple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ini_per', models.DateField()),
                ('fecha_fin_per', models.DateField()),
                ('n_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
